[ 15 ] Create validation login
shrimp-dev/RoleManager-flutter-frontend pull request #16
Opened 2022-01-29 12:58 UTC by GabrielAderaldo

**"PT-BR"** - **"Criando as validações do login."**

- Criando a classe de controller do login
- Criando as validações manuais do login

**"ENG"** - **"Creating login validations."**

- Creating the login controller class
- Creating manual login validations

2022-01-31 14:47 UTC, joaopedroalb requested changes

2022-01-31 14:47 UTC, joaopedroalb commented on rolemanager/lib/Controllers/login_controller.dart
> +    final emailRegExp = RegExp(r"^[a-zA-Z0-9.]+@[a-zA-Z0-9]+\.[a-zA-Z]+");
ENG:
Change regex to accept underline "**_**" in email case 

PT: 
Mudar o regex do email pra aceitar underline "**_**" também

2022-02-01 14:12 UTC, joaopedroalb approved these changes

2022-02-01 14:12 UTC, joaopedroalb commented on rolemanager/lib/Controllers/login_controller.dart
> +  static bool isPasswordValid(
ENG: 
Change name function to **isPasswordNotValid**

PT
Mudar o nome da função para **isPasswordNotValid**

2022-02-01 21:35 UTC, brenoc21 approved these changes

2022-02-01 21:36 UTC, merged